## Exercício

Você é um engenheiro de produção e tem os tempos de ciclo (em minutos) de uma linha de produção em um array NumPy. Seu trabalho é identificar quaisquer tempos de ciclo que estão dois desvios padrão acima ou abaixo da média. Use o seguinte array para sua análise: `tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])`. 

In [1]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo) 
print(media)

5.8


In [2]:
desvio_padrão = np.std(tempos_ciclo)
print(desvio_padrão)

0.592546294487706


In [5]:
condicao = (tempos_ciclo > media + 2 * desvio_padrão) | (tempos_ciclo < media - 2 * desvio_padrão)
anomalias = np.where(condicao)

print(anomalias)
print(tempos_ciclo[anomalias])

(array([7], dtype=int64),)
[7.2]


## Bônus


In [6]:
condicao = (tempos_ciclo > media + 2 * desvio_padrão) | (tempos_ciclo < media - 2 * desvio_padrão)
print(condicao)

[False False False False False False False  True False]


In [7]:
print(np.where(condicao))

(array([7], dtype=int64),)


In [10]:
contrario_condicao = ((tempos_ciclo <= media + 2 * desvio_padrão) & (tempos_ciclo >= media - 2 * desvio_padrão))
print(np.where(contrario_condicao))
print(np.where(~condicao))
print(~condicao)

(array([0, 1, 2, 3, 4, 5, 6, 8], dtype=int64),)
(array([0, 1, 2, 3, 4, 5, 6, 8], dtype=int64),)
[ True  True  True  True  True  True  True False  True]


## Bônus 2

In [11]:
rng = np.random.default_rng(seed=23)
tempos_gerados = rng.normal(loc=media, scale=desvio_padrão, size=100)
print(tempos_gerados)

[6.12783251 5.92893843 5.76563825 4.42592301 6.05568027 4.54008079
 6.33917045 6.15906265 6.29184699 6.29044959 5.97688364 5.48298689
 5.61805138 6.69360264 5.45500214 5.66482609 5.37069162 5.49350582
 5.61835026 5.95201873 5.62587668 5.58981881 5.43450847 5.85308294
 5.00351942 5.83092197 6.57625089 5.34556862 5.77310329 7.46932676
 5.21179446 4.8393986  5.54709583 6.8706944  7.00590016 5.07947125
 6.13783469 5.80267916 5.45136309 4.64708397 6.40711344 5.29009122
 5.9771759  5.84852596 6.90816898 6.49683135 5.1154099  5.64451872
 6.41438018 5.01012692 5.567551   5.9348492  4.8425482  5.06793385
 4.79025549 5.97004649 5.46727668 6.3502671  5.86742836 6.1389467
 5.75041819 6.24554966 5.7387798  5.21800011 6.50084502 6.3807002
 7.14312066 5.71573936 5.45638224 4.94256033 3.51319941 5.02471341
 6.08846253 5.2752818  4.26244665 6.16042204 5.44941554 5.58608836
 5.54435212 5.72018496 6.08113008 4.77221859 5.6654224  5.49863741
 6.47356202 5.18653839 6.77024208 6.16028782 6.76267642 5.382559

In [12]:
print(media)
print(tempos_gerados.mean())

5.8
5.7134800008241085


In [13]:
print(desvio_padrão)
print(tempos_gerados.std())

0.592546294487706
0.6514115912550178
